name: Artifacts Demo

on:
  workflow_dispatch:

jobs:
  job1:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Create a sample file
        run: echo "This is a test run." > file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: file  # ✅ Ensure this name is the same in download
          path: file.txt  # ✅ Keep the structure flat
          retention-days: 10

  job2:
    name: Download Artifacts
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: file  # ✅ Matches upload name
          path: downloaded  # ✅ Saves to this folder

      - name: Display the file content
        run: cat downloaded/file.txt  # ✅ Fix directory issue
