name : Custom Environment Variable


on:
    workflow_dispatch:

env:
    Day : Sunday
    testvar: value - 1

jobs:
    mainjob:
        name: 'print the env variable'
        runs-on: ubuntu-latest

        env:
          Greetings: Dear
          testvar: value - 2
        
          steps:
           - name: print-values-of-env-variable
             run: |
              echo "$Greetings  $First_name . Today is $Day"
              echo  "test var $testvar"
              echo "testvar  ${{env.testvar}}"
            env:
               First_name: Bharathan
               testvar: value-3
