name: Custom Environment Variable

on:
  workflow_dispatch:

env:  # Global Environment Variables
  Day: Sunday
  testvar: value-1

jobs:
  mainjob:
    name: 'Print the env variable'
    runs-on: ubuntu-latest

    env:  # Job-level Environment Variables
      Greetings: Dear
      testvar: value-2

    steps:
      - name: Print values of env variable
        env:  # Step-level Environment Variables
          First_name: Bharathan
          testvar: value-3
        run: |
          echo "$Greetings $First_name. Today is $Day"
          echo "Test var $testvar"
          echo "Test var (from env context) ${{ env.testvar }}"

      - name: Set a variable on the fly
        run: echo "My_variable = HELLO from Github Action" >> $GITHUB_ENV
      - name: Use the dynamic created variable
        run: echo "$My_variable"
