name: Github Environments

on:
    workflow_dispatch:

jobs:
    deployment:
        runs-on: ubuntu-latest

        environment:
            name: production
            url: https://github.com
        
        steps:
         - name: 'Print secret fom environment'
           run: |
             echo "MY_TOP_SECRET: ${{secrets.MY_TOP_SECRET}}"
