name: CI  # Workflow name

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Corrected action name

      - name: Run a one-line script  # Fixed indentation
        run: echo "Hello, World"

      - name: Run a multi-line script  # Fixed indentation
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
