name: Github Secret Actions

on:
    workflow_dispatch:

jobs:
    deployement:
        runs-on: ubuntu-latest
        steps:
            - name: Print Secret
              run: |
                echo "MY_TOP_SECRET: ${{secrets.MY_TOP_SECRET}}"
            - name: Print Secret as an Environment variable
              env:
                MY_TOP_SECRET: ${{secrets.MY_TOP_SECRET}}
              run: |
                echo "MY_TOP_SECRET: $MY_TOP_SECRET"